/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'BatchRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BatchRegistry__factory>
getContractFactory(name: 'BatchRegistryProxy', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BatchRegistryProxy__factory>
getContractFactory(name: 'IBatchRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IBatchRegistry__factory>

  getContractAt(name: 'BatchRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BatchRegistry>
getContractAt(name: 'BatchRegistryProxy', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BatchRegistryProxy>
getContractAt(name: 'IBatchRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IBatchRegistry>

  deployContract(name: 'BatchRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BatchRegistry>
deployContract(name: 'BatchRegistryProxy', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BatchRegistryProxy>
deployContract(name: 'IBatchRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IBatchRegistry>

  deployContract(name: 'BatchRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BatchRegistry>
deployContract(name: 'BatchRegistryProxy', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BatchRegistryProxy>
deployContract(name: 'IBatchRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IBatchRegistry>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  