/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace IBatchRegistry {
      
    export type SupplierRecordStruct = {dataHash: BytesLike, recordedBy: AddressLike, recordedAt: BigNumberish, isVerified: boolean, verifiedBy: AddressLike, verificationTimestamp: BigNumberish, productCount: BigNumberish, mongoDbId: string}

    export type SupplierRecordStructOutput = [dataHash: string, recordedBy: string, recordedAt: bigint, isVerified: boolean, verifiedBy: string, verificationTimestamp: bigint, productCount: bigint, mongoDbId: string] & {dataHash: string, recordedBy: string, recordedAt: bigint, isVerified: boolean, verifiedBy: string, verificationTimestamp: bigint, productCount: bigint, mongoDbId: string }
  
    }

  export interface IBatchRegistryInterface extends Interface {
    getFunction(nameOrSignature: "getSupplier" | "isSupplierVerified" | "recordSupplier" | "registeredSuppliers" | "totalSuppliers" | "updateProductCount" | "verifySupplier" | "verifySupplierHash"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "SupplierProductsUpdated" | "SupplierRecorded" | "SupplierVerified"): EventFragment;

    encodeFunctionData(functionFragment: 'getSupplier', values: [string]): string;
encodeFunctionData(functionFragment: 'isSupplierVerified', values: [string]): string;
encodeFunctionData(functionFragment: 'recordSupplier', values: [string, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'registeredSuppliers', values: [string]): string;
encodeFunctionData(functionFragment: 'totalSuppliers', values?: undefined): string;
encodeFunctionData(functionFragment: 'updateProductCount', values: [string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'verifySupplier', values: [string]): string;
encodeFunctionData(functionFragment: 'verifySupplierHash', values: [string, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'getSupplier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isSupplierVerified', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordSupplier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registeredSuppliers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSuppliers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateProductCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifySupplier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifySupplierHash', data: BytesLike): Result;
  }

  
    export namespace SupplierProductsUpdatedEvent {
      export type InputTuple = [mongoDbId: string, productCount: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [mongoDbId: string, productCount: bigint, timestamp: bigint];
      export interface OutputObject {mongoDbId: string, productCount: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SupplierRecordedEvent {
      export type InputTuple = [mongoDbId: string, dataHash: BytesLike, recorder: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [mongoDbId: string, dataHash: string, recorder: string, timestamp: bigint];
      export interface OutputObject {mongoDbId: string, dataHash: string, recorder: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SupplierVerifiedEvent {
      export type InputTuple = [mongoDbId: string, verifier: AddressLike, isVerified: boolean, timestamp: BigNumberish];
      export type OutputTuple = [mongoDbId: string, verifier: string, isVerified: boolean, timestamp: bigint];
      export interface OutputObject {mongoDbId: string, verifier: string, isVerified: boolean, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IBatchRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): IBatchRegistry;
    waitForDeployment(): Promise<this>;

    interface: IBatchRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getSupplier: TypedContractMethod<
      [mongoDbId: string, ],
      [IBatchRegistry.SupplierRecordStructOutput],
      'view'
    >
    

    
    isSupplierVerified: TypedContractMethod<
      [mongoDbId: string, ],
      [boolean],
      'view'
    >
    

    
    recordSupplier: TypedContractMethod<
      [mongoDbId: string, dataHash: BytesLike, productCount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    registeredSuppliers: TypedContractMethod<
      [mongoDbId: string, ],
      [boolean],
      'view'
    >
    

    
    totalSuppliers: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    updateProductCount: TypedContractMethod<
      [mongoDbId: string, newProductCount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    verifySupplier: TypedContractMethod<
      [mongoDbId: string, ],
      [boolean],
      'nonpayable'
    >
    

    
    verifySupplierHash: TypedContractMethod<
      [mongoDbId: string, dataHash: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getSupplier'): TypedContractMethod<
      [mongoDbId: string, ],
      [IBatchRegistry.SupplierRecordStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'isSupplierVerified'): TypedContractMethod<
      [mongoDbId: string, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'recordSupplier'): TypedContractMethod<
      [mongoDbId: string, dataHash: BytesLike, productCount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registeredSuppliers'): TypedContractMethod<
      [mongoDbId: string, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'totalSuppliers'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'updateProductCount'): TypedContractMethod<
      [mongoDbId: string, newProductCount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifySupplier'): TypedContractMethod<
      [mongoDbId: string, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifySupplierHash'): TypedContractMethod<
      [mongoDbId: string, dataHash: BytesLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'SupplierProductsUpdated'): TypedContractEvent<SupplierProductsUpdatedEvent.InputTuple, SupplierProductsUpdatedEvent.OutputTuple, SupplierProductsUpdatedEvent.OutputObject>;
getEvent(key: 'SupplierRecorded'): TypedContractEvent<SupplierRecordedEvent.InputTuple, SupplierRecordedEvent.OutputTuple, SupplierRecordedEvent.OutputObject>;
getEvent(key: 'SupplierVerified'): TypedContractEvent<SupplierVerifiedEvent.InputTuple, SupplierVerifiedEvent.OutputTuple, SupplierVerifiedEvent.OutputObject>;

    filters: {
      
      'SupplierProductsUpdated(string,uint256,uint256)': TypedContractEvent<SupplierProductsUpdatedEvent.InputTuple, SupplierProductsUpdatedEvent.OutputTuple, SupplierProductsUpdatedEvent.OutputObject>;
      SupplierProductsUpdated: TypedContractEvent<SupplierProductsUpdatedEvent.InputTuple, SupplierProductsUpdatedEvent.OutputTuple, SupplierProductsUpdatedEvent.OutputObject>;
    

      'SupplierRecorded(string,bytes32,address,uint256)': TypedContractEvent<SupplierRecordedEvent.InputTuple, SupplierRecordedEvent.OutputTuple, SupplierRecordedEvent.OutputObject>;
      SupplierRecorded: TypedContractEvent<SupplierRecordedEvent.InputTuple, SupplierRecordedEvent.OutputTuple, SupplierRecordedEvent.OutputObject>;
    

      'SupplierVerified(string,address,bool,uint256)': TypedContractEvent<SupplierVerifiedEvent.InputTuple, SupplierVerifiedEvent.OutputTuple, SupplierVerifiedEvent.OutputObject>;
      SupplierVerified: TypedContractEvent<SupplierVerifiedEvent.InputTuple, SupplierVerifiedEvent.OutputTuple, SupplierVerifiedEvent.OutputObject>;
    
    };
  }