/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BatchRegistry } from './BatchRegistry.js';
export type { BatchRegistryProxy } from './BatchRegistryProxy.js';
export type { IBatchRegistry } from './IBatchRegistry.js';
export * as factories from './factories/index.js';
export { BatchRegistry__factory } from './factories/BatchRegistry__factory.js';
export { BatchRegistryProxy__factory } from './factories/BatchRegistryProxy__factory.js';
export { IBatchRegistry__factory } from './factories/IBatchRegistry__factory.js';