/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IBatchRegistry, IBatchRegistryInterface } from "../IBatchRegistry.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "string",
        "name": "mongoDbId",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "productCount",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "SupplierProductsUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "string",
        "name": "mongoDbId",
        "type": "string"
      },
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "dataHash",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "recorder",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "SupplierRecorded",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "string",
        "name": "mongoDbId",
        "type": "string"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "verifier",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "isVerified",
        "type": "bool"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "SupplierVerified",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "mongoDbId",
        "type": "string"
      }
    ],
    "name": "getSupplier",
    "outputs": [
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "dataHash",
            "type": "bytes32"
          },
          {
            "internalType": "address",
            "name": "recordedBy",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "recordedAt",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "isVerified",
            "type": "bool"
          },
          {
            "internalType": "address",
            "name": "verifiedBy",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "verificationTimestamp",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "productCount",
            "type": "uint256"
          },
          {
            "internalType": "string",
            "name": "mongoDbId",
            "type": "string"
          }
        ],
        "internalType": "struct IBatchRegistry.SupplierRecord",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "mongoDbId",
        "type": "string"
      }
    ],
    "name": "isSupplierVerified",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "mongoDbId",
        "type": "string"
      },
      {
        "internalType": "bytes32",
        "name": "dataHash",
        "type": "bytes32"
      },
      {
        "internalType": "uint256",
        "name": "productCount",
        "type": "uint256"
      }
    ],
    "name": "recordSupplier",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "mongoDbId",
        "type": "string"
      }
    ],
    "name": "registeredSuppliers",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "totalSuppliers",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "mongoDbId",
        "type": "string"
      },
      {
        "internalType": "uint256",
        "name": "newProductCount",
        "type": "uint256"
      }
    ],
    "name": "updateProductCount",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "mongoDbId",
        "type": "string"
      }
    ],
    "name": "verifySupplier",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "mongoDbId",
        "type": "string"
      },
      {
        "internalType": "bytes32",
        "name": "dataHash",
        "type": "bytes32"
      }
    ],
    "name": "verifySupplierHash",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IBatchRegistry__factory {
    static readonly abi = _abi;
    static createInterface(): IBatchRegistryInterface {
      return new Interface(_abi) as IBatchRegistryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IBatchRegistry {
      return new Contract(address, _abi, runner) as unknown as IBatchRegistry;
    }
  }
  