/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BatchRegistry__factory } from './BatchRegistry__factory.js';
export { BatchRegistryProxy__factory } from './BatchRegistryProxy__factory.js';
export { IBatchRegistry__factory } from './IBatchRegistry__factory.js';